# Generated by Django 4.2.4 on 2023-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackapp', '0003_remove_f_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
