# Generated by Django 4.2.4 on 2023-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackapp', '0012_cart_order_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
