# Generated by Django 4.2.5 on 2023-12-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackapp', '0014_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
